name: mini
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_toggle_tab: ^1.4.1
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/image/3resister.png
    - assets/image/3resister2.png
    - assets/image/3resister3.png
    - assets/image/4resister4.png
  uses-material-design: true
